name: Build and Measure C++ Program Runtime

# 触发条件：推送代码到 main 分支时触发
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2: 安装必要的编译工具
      - name: Install dependencies
        run: |
          choco install mingw  # 安装 MinGW 作为 C++ 编译器

      # 步骤 3: 编译 C++ 程序
      - name: Compile C++ program
        run: |
           g++ -O0 -march=native -mavx2 -std=c++20 -o opt .\main.cpp  # 编译 C++ 程序

      # 步骤 4: 运行程序并计算运行时间
      - name: Measure runtime
        run: |
           .\opt.exe 2333
